name: Build & deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: "ubuntu-20.04"

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v2"

    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        php-version: "8.1"

    - name: "Install dependencies with Composer"
      uses: "ramsey/composer-install@v1"
      with:
        dependency-versions: "highest"

    - name: Install optipng
      run: sudo apt install -y optipng

    - name: Install jpegoptim
      run: sudo apt install -y jpegoptim

    - name: "Run Jug"
      run: "vendor/bin/jug build"
      
    - name: "Depoy"
      run: "./deploy.sh"
